### ISSUE TITLE
Flutter App Production

### ISSUE THREAD

**Issue by LucasTesnier** [Epitech-Nantes-Tek3/A-equals-l-squared#104]
**Short description:**

Change the current Flutter app state from Development to Production.

**Describe the solution you'd like**
Rename the Application (From Application to AEqualLSquared), update her BitLogo and change the release mode from Debug to Production (It will remove the red banner "Debug" from the upper corner

**Comment by TomDUVAL-MAHE** [comment]
If I want to develop the front, I do this on this branch or on another ?

**Comment by LucasTesnier** [comment]
This issue is not useful for the moment. It will be at the project end and will consist on updating the Application Logo, rename it and change her release mode.

**Comment by LucasTesnier** [comment]
This issue is not useful for the moment. It will be at the project end and will consist on updating the Application Logo, rename it and change her release mode.

**Comment by TomDUVAL-MAHE** [comment]
:+1:
